### PR TITLE
submit my blogo generator

### PR DESCRIPTION
**Pull request by kevin14**
hi , here is my blog generator.
based on javascript and jade
-v-

### CODE REVIEW

**Comment by biilmann** [comment]
Happy to add it, but we'll need description and body text in english for consistency.

**Comment by kevin14** [comment]
Thanks,i got it. 
I will pull-request an English version later.

**Comment by kevin14** [comment]
@biilmann hi , i've modified my description and body text. Thanks.

**Comment by biilmann** [comment]
Great! Merged in!

**Comment by kevin14** [comment]
Thank you very much!!!

**Pull request merged**
